<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Moji.Infrastructure\Moji.Infrastructure.csproj" />
    <ProjectReference Include="..\Moji.Application\Moji.Application.csproj" />
    <ProjectReference Include="..\Moji.Domain\Moji.Domain.csproj" />
  </ItemGroup>

</Project>
